apiVersion: v1
kind: Pod
metadata:
  name: dynamic-photo
spec:
  containers:
  - image: sonambewafaa/photos-app:v2
    name: photo-app
    ports:
    - containerPort: 8501
    volumeMounts:
    - mountPath: /app/photos
      name: dynamic-vol
  volumes: 
  - persistentVolumeClaim:
      claimName: dynamic-pvc
    name: dynamic-vol

  