apiVersion: v1
kind: Pod
metadata:
  name: photo-app
spec:
  containers:
  - image: sonambewafaa/photos-app:v2
    name: photo-app
    ports:
    - containerPort: 8501
    volumeMounts:
    - mountPath: /app/photos
      name: pod-vol
  volumes: 
  - persistentVolumeClaim:
      claimName: pvc-chandan
    name: pod-vol

  