apiVersion: v1
kind:  PersistentVolume
metadata: 
  name: blob-pv
spec:
  accessModes: 
  -  ReadWriteMany
  capacity: 
    storage: 1Gi
  azureFile: 
    secretName: pv-secret
    shareName: pv-fileshare
  storageClassName: ""
  

