apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  pvc-chandan 
spec:
  accessModes: 
  -  ReadWriteMany
  resources:
    requests:
       storage: 1Gi
  volumeMode: Filesystem
  volumeName: blob-pv
  storageClassName: ""

